-   id: hook_golangci_lint
    name: hook_golangci_lint
    description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"
    entry: cmd/hook_golangci_lint.go
    files: '\.go$'
    types: [ go ]
    language: golang